Window:
    Title: Car2D
    Width: 800
    Height: 600

Camera:
    ZoomLevel: 20.0
    
Controls:
    Accelerate:
        - W
        - Up
    Reverse:
        - S
        - Down
    Left:
        - A
        - Left
    Right:
        - D
        - Right
    ParkingBrake:
        - Space
    GearUp:
        - R
    GearDown:
        - F
    ToggleAutomatic:
        - T
        
World:
    Gravity: 9.82
    
Assets:
    DefaultCar: test_car.yaml
    DefaultMap: test_map.yaml