Window:
    Title: Car2D
    Width: 800
    Height: 600

Camera:
    ZoomLevel: 40.0
    MaxZoomLevel: 150.0
    MinZoomLevel: 10.0
    
Controls:
    Accelerate:
        - W
        - Up
    Reverse:
        - S
        - Down
    Left:
        - A
        - Left
    Right:
        - D
        - Right
    HandBrake:
        - Space
    GearUp:
        - R
    GearDown:
        - F
    ToggleAutomatic:
        - T
        
World:
    Gravity: 9.82
    AirDensity: 1.2754
    
Assets:
    DefaultCar: test_car.yaml
    DefaultMap: test_map.yaml