Window: {
    Width: 800
    Height: 600
    Windowed: true
}

Controls: {
    Accelerate:
        - W
        - Up
    Reverse:
        - S
        - Down
    Left:
        - A
        - Left
    Right:
        - D
        - Right
}